"""
Applying machine learning algorithms to data generated from :mod:`~src.shaft` to
create a model for track movement prediction.

This module provides functionalities to develop and evaluate machine learning models that predict
track movement based on data generated by the :mod:`~src.shaft` module. It includes classes for
further processing data, training machine learning models, evaluating model performance, and
visualising results.

.. seealso::

    - Documentation of the :mod:`~src.shaft` module.
    - Example usage in the method :meth:`~src.modeller.prototype.TrackMovementEstimator.classifier`.
"""

from .prototype import TrackMovementEstimator

__all__ = ['TrackMovementEstimator']
